### ISSUE TITLE
How to trigger set_field_value?

### ISSUE THREAD

**Issue by jandreaucodes** [pinuz95/alfred-asana-tracker#2]
In looking at api.py, it looks like there's a function for `set_field_value`, but nothing in the workflow to use it.

Am I missing something, or is this function not implemented in the workflow itself?

**Comment by pinuz95** [comment]
It's used in the function [stop_task](https://github.com/pinuz95/alfred-asana-tracker/blob/9b550b875994d5e4d787ec30900630cdd300eb3c/utils.py#L43), and it's needed to update the field to track the hours spent on a task.
